/**
 * NexRoute - Mock AI Service Providers Endpoints
 * Simulates 3 AI providers with varying latency, pricing, failure rates, and contextual outputs.
 */

const express = require('express');
const router = express.Router();
const state = require('../data/state');

/**
 * Generates dynamic, contextual AI response based on query content
 */
function generateContextualResponse(query = "", providerName = "") {
  const q = String(query).toLowerCase();

  if (q.includes("flight") || q.includes("tokyo") || q.includes("plane") || q.includes("airline")) {
    return `Flight itinerary found for '${query}': Tokyo Express, Departure 08:00 AM, Economy Class ($850)`;
  }
  if (q.includes("hotel") || q.includes("stay") || q.includes("resort") || q.includes("room")) {
    return `Hotel options retrieved for '${query}': Grand Hyatt Tokyo, 4.8 Stars, Deluxe King ($220/night)`;
  }
  if (q.includes("code") || q.includes("script") || q.includes("function") || q.includes("bug")) {
    return `Code generated for '${query}': function executeRouting() { return { status: 'success' }; }`;
  }
  if (q.includes("translate") || q.includes("japanese") || q.includes("language")) {
    return `Translation result for '${query}': "こんにちは、世界！" (Hello, World!)`;
  }
  if (q.includes("summary") || q.includes("summarize") || q.includes("article")) {
    return `Executive summary generated for '${query}': Key insights compiled into 3 action items.`;
  }

  return `AI response generated by ${providerName} for query '${query}': Task processed successfully with high precision.`;
}

/**
 * Helper to simulate network latency with slight randomness and optional failure
 */
async function simulateProviderExecution(req, res, config) {
  const startTime = Date.now();
  const { minDelay, maxDelay, price, providerName } = config;

  // Calculate random latency within range
  const delay = Math.floor(Math.random() * (maxDelay - minDelay + 1)) + minDelay;
  await new Promise(resolve => setTimeout(resolve, delay));

  // Check if force failure query/header parameter is provided
  const forceFailure = req.query.forceFailure === "true" || req.headers["x-force-failure"] === "true";
  
  // Check if random failure is disabled via state or query/header override
  const disableFailures = state.getDisableFailures() || 
                          req.query.disableFailures === "true" || 
                          req.headers["x-disable-failures"] === "true";

  // Trigger failure if forced, or 5% random chance (unless failures are disabled)
  if (forceFailure || (!disableFailures && Math.random() < 0.05)) {
    return res.status(500).json({
      status: "error",
      message: `Simulated 500 error from ${providerName}`,
      provider: providerName
    });
  }

  const processingTimeMs = Date.now() - startTime;
  const query = req.body && req.body.query ? req.body.query : "general task";
  const resultText = generateContextualResponse(query, providerName);

  return res.status(200).json({
    result: resultText,
    price: price,
    provider: providerName,
    processingTime: `${processingTimeMs}ms`
  });
}

// POST /provider-a/service — Budget Provider (800-900ms delay, $0.001)
router.post('/provider-a/service', async (req, res) => {
  try {
    await simulateProviderExecution(req, res, {
      minDelay: 800,
      maxDelay: 900,
      price: 0.001,
      providerName: "Provider A"
    });
  } catch (err) {
    res.status(500).json({ status: "error", message: err.message });
  }
});

// POST /provider-b/service — Premium Fast Provider (100-150ms delay, $0.005)
router.post('/provider-b/service', async (req, res) => {
  try {
    await simulateProviderExecution(req, res, {
      minDelay: 100,
      maxDelay: 150,
      price: 0.005,
      providerName: "Provider B"
    });
  } catch (err) {
    res.status(500).json({ status: "error", message: err.message });
  }
});

// POST /provider-c/service — Balanced Provider (350-450ms delay, $0.003)
router.post('/provider-c/service', async (req, res) => {
  try {
    await simulateProviderExecution(req, res, {
      minDelay: 350,
      maxDelay: 450,
      price: 0.003,
      providerName: "Provider C"
    });
  } catch (err) {
    res.status(500).json({ status: "error", message: err.message });
  }
});

module.exports = router;
